print('============   DESAFIO 009  ============')
# Faça um programa que leia um número inteiro qualquer e mostre na tela a sua tabuada.
n = int(input('Escolha um número que deseja ver a tabuada:'))
print('--------------------------------------')
print('{} * 0 = {}\n{} * 1 = {}\n{} * 2 = {}\n{} * 3 = {}\n{} * 4 = {}\n{} * 5 = {}\n{} * 6 = {}\n{} * 7 = {}\n{} * 8 = {}\n{} * 9 = {}\n{} * 10 = {}'.format(n, n*0,n, n*1,n, n*2,n, n*3,n, n*4,n, n*5,n, n*6,n, n*7,n, n*8,n, n*9,n, n*10))
print('==================OU=================')
print('{} * {:2} = {}'.format(n, 0, n*0))
print('{} * {:2} = {}'.format(n, 1, n*1))
print('{} * {:2} = {}'.format(n, 2, n*2))
print('{} * {:2} = {}'.format(n, 3, n*3))
print('{} * {:2} = {}'.format(n, 4, n*4))
print('{} * {:2} = {}'.format(n, 5, n*5))
print('{} * {:2} = {}'.format(n, 6, n*6))
print('{} * {:2} = {}'.format(n, 7, n*7))
print('{} * {:2} = {}'.format(n, 8, n*8))
print('{} * {:2} = {}'.format(n, 9, n*9))
print('{} * {:2} = {}'.format(n, 10, n*10))
print('--------------------------------------')
print('CONCLUIDO!!!')